var testCase = require('mocha').describe;
var pre = require('mocha').before;
var assertions = require('mocha').it;
var assert = require('assert');
var JSON = {
    "family": "AUDIT AND ACCOUNTABILITY",
    "number": "AU-8",
    "title": "TIME STAMPS",
    "priority": "P1",
    "baseline-impact": ["LOW", "MODERATE", "HIGH"],
    "statement": {
        "description": "The information system:",
        "statement": [{
            "number": "AU-8a.",
            "description": "Uses internal system clocks to generate time stamps for audit records; and"
        }, {
            "number": "AU-8b.",
            "description": "Records time stamps for audit records that can be mapped to Coordinated Universal Time (UTC) or Greenwich Mean Time (GMT) and meets [Assignment: organization-defined granularity of time measurement]."
        }]
    },
    "supplemental-guidance": {
        "description": "Time stamps generated by the information system include date and time. Time is commonly expressed in Coordinated Universal Time (UTC), a modern continuation of Greenwich Mean Time (GMT), or local time with an offset from UTC. Granularity of time measurements refers to the degree of synchronization between information system clocks and reference clocks, for example, clocks synchronizing within hundreds of milliseconds or within tens of milliseconds. Organizations may define different time granularities for different system components. Time service can also be critical to other security capabilities such as access control and identification and authentication, depending on the nature of the mechanisms used to support those capabilities.",
        "related": ["AU-3", "AU-12"]
    },
    "control-enhancements": {
        "control-enhancement": [{
            "number": "AU-8 (1)",
            "title": "SYNCHRONIZATION WITH AUTHORITATIVE TIME SOURCE",
            "baseline-impact": ["MODERATE", "HIGH"],
            "statement": {
                "description": "The information system:",
                "statement": [{
                    "number": "AU-8 (1)(a)",
                    "description": "Compares the internal information system clocks [Assignment: organization-defined frequency] with [Assignment: organization-defined authoritative time source]; and"
                }, {
                    "number": "AU-8 (1)(b)",
                    "description": "Synchronizes the internal system clocks to the authoritative time source when the time difference is greater than [Assignment: organization-defined time period]."
                }]
            },
            "supplemental-guidance": {
                "description": "This control enhancement provides uniformity of time stamps for information systems with multiple system clocks and systems connected over a network."
            }
        }, {
            "number": "AU-8 (2)",
            "title": "SECONDARY AUTHORITATIVE TIME SOURCE",
            "statement": {
                "description": "The information system identifies a secondary authoritative time source that is located in a different geographic region than the primary authoritative time source."
            }
        }]
    }
}
//Control Families
describe(JSON.family, function() {
    // description": "Time stamps generated by the information system include date and time. Time is commonly expressed in Coordinated Universal Time (UTC), a modern continuation of Greenwich Mean Time (GMT), or local time with an offset from UTC. Granularity of time measurements refers to the degree of synchronization between information system clocks and reference clocks, for example, clocks synchronizing within hundreds of milliseconds or within tens of milliseconds. Organizations may define different time granularities for different system components. Time service can also be critical to other security capabilities such as access control and identification and authentication, depending on the nature of the mechanisms used to support those capabilities.
    describe(JSON.number + " - " + JSON.title, function() {
        var ntpClient = require('ntp-client');
        it("should be reasonably close (<9ms) to ntp", function(done) {
            ntpClient.getNetworkTime("pool.ntp.org", 123, function(err, ntp_date) {
                sys_date = new Date()
                
                if (sys_date.getTime().toPrecision(11) === ntp_date.getTime().toPrecision(11)){
                    done()
                } else {
                    throw new Error(err + " ntp server not responding or not sync'd, please check configuration"
                                   + " system time " + sys_date.getTime().toPrecision(11)+ " ntp time "
                                    +ntp_date.getTime().toPrecision(11))
                }
            });
        });
    });   
});

